The-Royal-Flash/royal-flash-express

- src/models/QuestionCard.ts
- src/models/Quizlet.ts
- src/models/StudyLog.ts
- src/models/User.ts
Schema - (QuestionCard, Quizlet, StudyLog, User) 구성
> Feat: Schema

- nodemon.json
- package.json
- src/models/QuestionCard.ts
- src/models/Quizlet.ts
- src/models/StudyLog.ts
- src/models/User.ts
Schema - (Quizlet, StudyLog) 인터페이스 수정
Package.json - 실행 scripts 수정 (nodemon watch 오류 수정)
> Fix: Schema

- package-lock.json
- package.json
- src/api/api.ts
- src/api/auth/auth.ts
- src/api/auth/authController.ts
- src/models/User.ts
- src/routes/apiRouter.ts
- src/server.ts
API - 라우팅 및  Auth(회원가입, 이메일 & 닉네임 중복확인) 구현
Schema - User 스키마(비빌번호 해쉬 암호화) 구현
> Feat: Auth API

- src/api/auth/authController.ts
API - Auth (회원가입, 이메일 & 닉네임 중복확인) 수정
> Feat: auth API 수정 - (회원가입, 중복확인)

- package-lock.json
- package.json
- src/api/auth/auth.ts
- src/api/auth/authController.ts
- src/middlewares/authTokenMiddleware.ts
- src/server.ts
API - Auth (로그인, 로그아웃) 구현
Middleware - JWT 토큰 인증 Middleware 구현 (accessToken, refreshToken)
> Feat: Auth API (로그인, 로그아웃) & JWT 인증 Middleware

- src/api/api.ts
- src/api/controllers/authController.ts
- src/api/routes/auth.ts
> -: API 폴더구조 변경

- src/api/api.ts
- src/api/controllers/authController.ts
- src/api/controllers/profileController.ts
- src/api/routes/profile.ts
- src/utils/createJWT.ts
**Feat**
- Profile api 라우팅
- JWT Middleware 적용
- Profile 정보, 이름 변경, 닉네임 변경 구현
> Feat: Profile API

- .gitignore
- src/api/controllers/authController.ts
- src/api/controllers/profileController.ts
- src/api/routes/profile.ts
Feat
- Profile API (비밀번호 변경)
Fix
- Auth API (로그아웃 에러 수정)
> Feat: Profile API (비밀번호 변경)

- src/api/api.ts
- src/api/controllers/quizlet.controller.ts
- src/api/routes/quizlet.ts
Feat
Quizlet API - 학습세트 생성, 학습세트 삭제
Profile API - 비밀번호 변경
> Feat: Quizlet API (학습세트 생성, 삭제)

- src/api/controllers/authController.ts
- src/api/controllers/profileController.ts
- src/api/controllers/quizlet.controller.ts
- src/models/StudyLog.ts
Refac
- api 에러처리 수정 (전체)
- 데이터 처리 일부 수정 (학습세트 생성, 삭제)
- 반환 데이터 수정 (프로필 정보)
> Refac: API & DB Model

- src/api/controllers/quizlet.controller.ts
- src/api/routes/quizlet.ts
Feat
- Quizlet API (학습세트 정보, 학습세트 수정)
> Feat: Quizlet API - 학습세트 정보, 학습세트 수정

- src/api/controllers/quizlet.controller.ts
- src/api/controllers/quizletController.ts
- src/api/routes/quizlet.ts
Refac
- 학습세트 생성(리스폰 수정)
- 학습세트 정보(라우터 수정)
요청사항 반영✔
> Refac: Quizlet API - 학습세트 생성, 학습세트 정보

- src/api/controllers/quizletController.ts
- src/api/routes/quizlet.ts
- src/models/StudyLog.ts
- src/models/User.ts
Feat
학습세트 상세
모든 학습세트 태그 목록
나의 학습세트 태그 목록
Refac
학습세트 수정 (questionCardsToAdd = req.body -> questionCardListToAdd = req.body) [FE 요청]
> Feat: Quizlet API - 학습세트 상세, 모든 학습세트 태그 목록, 나의 학습세트 태그 목록

- src/api/controllers/quizletController.ts
- src/api/routes/quizlet.ts
- src/models/StudyLog.ts
- src/server.ts
Feat
- Quizlet API - 학습정보 제출
Server
- Cors 미들웨어 수정
> Feat: Quizlet API - 학습정보 제출

- src/api/api.ts
- src/api/controllers/quizletController.ts
- src/api/controllers/searchController.ts
- src/api/routes/search.ts
> Feat: Search API - 검색

- src/api/controllers/authController.ts
- src/api/routes/auth.ts
Refac
- 이메일 중복체크, 닉네임 중복체크 (POST 메서드로 변경)
- 로그아웃 (GET 메서드로 변경)
- 로그인 Response 변경
> Refac: Auth API - 라우팅 메서드 수정, 로그인(리스폰) 수정

- src/api/controllers/auth.controller.ts
- src/api/controllers/profile.controller.ts
- src/api/controllers/quizlet.controller.ts
- src/api/controllers/quizletController.ts
- src/api/controllers/search.controller.ts
- src/api/routes/auth.ts
- src/api/routes/profile.ts
- src/api/routes/quizlet.ts
- src/api/routes/search.ts
- src/models/StudyLog.ts
- src/models/User.ts
- src/utils/createJWT.ts
!BREAKING CHANGE
User 모델 - ( studyLog 필드 삭제 )
StudyLog 모델 - owner: [User 모델의 uuid] 필드 추가, updateAt 필드 삭제
All controller - 파일명 변경
profile.controller - jwt.payload 수정 ( 이름 변경, 닉네임 변경, Avatar 업로드 )
quizlet.controller - 모든 로직 변경
search.controller - 전체 학습세트 검색 ( req.query.tagList: string -> string[] 변환 추가 )
Feat
quizlet.controller - 학습세트 문제
> !BREAKING CHANGE: API 컨트롤러 수정

- src/api/controllers/quizlet.controller.ts
- src/utils/jwt-util.ts
Fix
quizlet.controller - 학습세트 상세(토큰 검증 오류)
> Fix: jwt - 토큰 검증 오류

- src/api/controllers/search.controller.ts
- 학습세트 정렬 오류 수정 (정렬 기준: 학습세트 마지막 점수 오름차순/내림차순)
> Fix: 학습세트 정렬 오류 수정

- .eslintrc.json
- .prettierrc.json
- package-lock.json
- package.json
- src/api/api.ts
- src/api/controllers/auth.controller.ts
- src/api/controllers/profile.controller.ts
- src/api/controllers/quizlet.controller.ts
- src/api/controllers/search.controller.ts
- src/api/routes/auth.ts
- src/api/routes/profile.ts
- src/api/routes/quizlet.ts
- src/api/routes/search.ts
- src/constants/study.ts
- src/db.ts
- src/init.ts
- src/middlewares/authTokenMiddleware.ts
- src/middlewares/uploadAvatarMiddleware.ts
- src/models/QuestionCard.ts
- src/models/Quizlet.ts
- src/models/RefreshToken.ts
- src/models/StudyLog.ts
- src/models/User.ts
- src/server.ts
- src/utils/jwt-util.ts
- src/utils/utils.ts
-:
eslint, prettier 적용
Fix:
quizlet.controller 
- 간이 학습기록 삭제
- 학습세트 populate 오류 수정
search.controller
- 검색 조건 수정(태그로 검색 시 오류 수정)
- 나의 학습 검색 Response 수정
> Fix: FE request

- package-lock.json
- package.json
- src/api/controllers/profile.controller.ts
- src/api/routes/profile.ts
- src/middlewares/uploadAvatarMiddleware.ts
- src/s3/multer.config.ts
- src/s3/s3.config.ts
Feat:
profile.controller - 아바타 업로드(S3 스토리지 연동)
> Feat: AWS S3 스토리지

- package-lock.json
- package.json
-:
add forever
package.json - 스크립트 수정
> Dist: server

- src/api/controllers/auth.controller.ts
- src/api/controllers/quizlet.controller.ts
- src/middlewares/authTokenMiddleware.ts
> Fix: Cors 에러 수정

- src/api/routes/search.ts
Feat:
search.controller - getOwnedQuizlet 추가
> Feat: 생성한 학습세트 검색

- .github/workflows/deploy-main.yml
Dist:
github actions - deploy-main.yml 수정
> Dist: github actions - 수정

- package-lock.json
- package.json
- src/middlewares/uploadAvatarMiddleware.ts
Fix:
AWS S3 - Content-Type 오류 수정
> Fix: AWS S3 - Content-Type 오류 수정

- package-lock.json
- package.json
> -: @types/mime 추가

- src/server.ts
> Fix: Cors - 메서드 수정
